In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [1]:
with open("/content/fake_train.csv", 'r') as f:
    lines = f.readlines()

print(lines[4645:4655])

['5. Their SAFE support will allow you to ask questions directly to the team and Luc himself as well as connect, discuss and collaborate with other participants. To share this essential knowledge throughout the world, Solution Era needs your contribution to complete the course videos, edit the content and translate the material. Let’s support their amazing efforts in creating a healthier and more sustainable world for generations to come!",1\n', '578,"SHERIFF CLARKE On Obama’s Final Days: “Obama’s Like A Tenant Who’s Been Evicted From A Property, And He’s Gonna Trash The Place On The Way Out The Door” [VIDEO]",EdJenner,"Go to Article Wow! Milwaukee’s Sheriff David Clarke nails it again! “[President] Obama is like a tenant who has been evicted from a property, and he’s going to trash the place on the way out the door just out of spite. So, nothing would surprise me from Obama in these waning days.” — Sheriff David Clarke  ",1\n', '579,45 Weird Bans on Women in Iran,Dr. Majid Rafizadeh,"

In [4]:

df = pd.read_csv("/content/fake_train.csv")

In [6]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
df.shape

(20800, 5)

In [9]:
df=df.dropna()

In [10]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [13]:
## Get the independent features
x=df.drop('label', axis=1)

In [14]:
y=df['label']

In [15]:
x

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [16]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [17]:
### Check whether the dataset is balanced or not
y.value_counts()

label
0    10361
1     7924
Name: count, dtype: int64

In [21]:
pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [25]:
pip install tensorflow

In [26]:
import tensorflow as tf

In [27]:
tf.__version__

'2.18.0'

In [29]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [30]:
## Vocabulary size
voc_size=5000

In [31]:
messages=x.copy()

In [32]:
messages.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get the feeling your life circles the rou...  
2   Why the Truth Might Get You Fired October 29, ...  
3   Videos 15 Civilians Killed In Single US Airstr...  
4   Print \nAn Iranian woman has been sentenced to...  
5   In these trying times, Jackie Mason is the Voi...  
7   PARIS  —   France chose an idealistic, traditi...  
9   A week before Michael T. Flynn resigned as nat...  
10  Organizing for Action, the activist group that...  
11  The BBC produced spoof on the “Real Housewives...

In [33]:
import nltk
import re
from nltk.corpus import stopwords

In [34]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [35]:
messages.reset_index(inplace=True)

In [39]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
   # review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = re.sub('[^a-zA-Z]', ' ', messages['title'].iloc[i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [40]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [42]:
### Convert into binarry by applying One Hot
onehot_repr=[one_hot(words,voc_size)for words in corpus]


In [43]:
onehot_repr

[[2082, 1455, 3521, 4900, 4186, 2975, 4226, 2680, 373, 63],
 [1385, 4188, 1786, 4923, 4174, 2037, 3609],
 [4333, 929, 1773, 222],
 [695, 2339, 4225, 2085, 4494, 1345],
 [2297, 4174, 2762, 1197, 2584, 3230, 4174, 1720, 4725, 1744],
 [1381,
  4837,
  4200,
  544,
  2903,
  1244,
  2682,
  2851,
  2846,
  2545,
  1588,
  1699,
  3599,
  2404,
  3609],
 [4004, 3249, 1277, 2729, 2809, 2874, 3524, 4220, 3702, 1851, 3452],
 [4238, 3699, 1955, 2970, 1493, 2340, 1244, 2368, 3702, 1851, 3452],
 [4890, 4153, 1453, 4569, 4676, 332, 1119, 1152, 1244, 2979],
 [1045, 235, 4798, 1034, 3758, 918, 4090, 2676],
 [4347, 1772, 510, 4747, 2292, 2443, 4779, 4144, 1333, 295, 504],
 [2085, 388, 4186, 332, 1244, 1493],
 [4191, 3357, 4559, 3086, 3784, 1487, 4371, 2892, 807],
 [1090, 882, 2283, 2555, 3785, 4441, 28, 3702, 1851, 3452],
 [1533, 1470, 51, 3497, 4198, 3702, 1851, 3452],
 [1429, 3288, 4302, 4163, 3738, 4710, 4919, 4733, 2910, 2494],
 [471, 98, 4188],
 [4969, 3836, 270, 4886, 1244, 4629, 4191, 3609],
 

In [44]:
onehot_repr[1]

[1385, 4188, 1786, 4923, 4174, 2037, 3609]

# Embedding Representation

In [45]:
sent_length=20
embedded_doc=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_doc)

[[   0    0    0 ... 2680  373   63]
 [   0    0    0 ... 4174 2037 3609]
 [   0    0    0 ...  929 1773  222]
 ...
 [   0    0    0 ... 3702 1851 3452]
 [   0    0    0 ... 2035 2141 3285]
 [   0    0    0 ... 2759 4256 3316]]


In [52]:
## Creating model


In [50]:
print("Vocabulary Size:", voc_size)
print("Sentence Length:", sent_length)


Vocabulary Size: 5000
Sentence Length: 20


In [51]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Input

voc_size = 5000
sent_length = 20
embedded_vector_features = 40

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, embedded_vector_features))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_4 (Bidirectional) │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 313,001 (1.19 MB)

 Trainable params: 313,001 (1.19 MB)

 Non-trainable params: 0 (0.00 B)

None


In [53]:
import numpy as np
x_final=np.array(embedded_doc)
y_final=np.array(y)

In [54]:
## Train test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.33, random_state=42)
#

In [55]:
## model Training
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 26s 106ms/step - accuracy: 0.7790 - loss: 0.4104 - val_accuracy: 0.9084 - val_loss: 0.2267
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 45s 130ms/step - accuracy: 0.9465 - loss: 0.1408 - val_accuracy: 0.9203 - val_loss: 0.2088
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 21s 109ms/step - accuracy: 0.9691 - loss: 0.0902 - val_accuracy: 0.9143 - val_loss: 0.2250
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 14s 74ms/step - accuracy: 0.9807 - loss: 0.0551 - val_accuracy: 0.9112 - val_loss: 0.2616
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.9880 - loss: 0.0374 - val_accuracy: 0.9170 - val_loss: 0.3225
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 20s 73ms/step - accuracy: 0.9906 - loss: 0.0294 - val_accuracy: 0.9115 - val_loss: 0.3869
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - accuracy: 0.9933 - loss: 0.0187 - val_accuracy: 0.9130 - val_loss: 0.4435
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 15s 76ms/step - accuracy: 0.9960 - loss: 0.0110

In [56]:
y_pred=model.predict(x_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step


In [57]:
y_pred=np.where(y_pred > 0.5, 1, 0)

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[3126,  293],
       [ 274, 2342]])

In [59]:
print(accuracy_score(y_test, y_pred))

0.9060480530240265


In [60]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92      3419
           1       0.89      0.90      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.91      0.91      0.91      6035

